@echo off
echo Adding all files including deletions...
git add --all
echo Checking status...
git status
echo Committing all changes...
git commit -m "Complete IFCS implementation: Signal estimation engine, 3-gate pipeline, CP-2 topic gating, all 36 taxonomy tests passing (100%% success rate with real LLM)"
echo Pushing to remote...
git push origin master
echo All done!