@echo off
echo Adding all files...
git add .
echo Committing changes...
git commit -m "Complete IFCS implementation: Signal estimation, 3-gate pipeline, CP-2 topic gating, 36 taxonomy tests (100%% success)"
echo Pushing to remote...
git push origin master
echo Done!